maxLikes: 2000
minLikes: 10
maxFollowers: 100000
minFollowing: 30
minFollowers: 30
whiteList:
  - nasa
  - natgeo
  - spacex
  - natural_history_museum
  - wtofficial
  - nightwish
  - dukeuniversity
